language: r
warnings_are_errors: false
notifications:
  email: false
sudo : true
r:
  - release
  - devel
apt_packages: 
  - git
before_install:
  - sudo /usr/bin/Xvfb :99 -ac -screen 0 1024x768x8 &>/dev/null & export DISPLAY=":99" &>/dev/null
  - git clone https://github.com/freemed/tty0tty.git
  - cd tty0tty
  - make
  - cd module
  - make
  - sudo cp tty0tty.ko /lib/modules/$(uname -r)/kernel/drivers/misc 
  - sudo depmod 
  - sudo modprobe tty0tty
  - sudo chmod 666 /dev/tnt* 
  - cd ~