language: r
warnings_are_errors: false
notifications:
  email: false
sudo : true
cache: packages
r:
  - release
  - devel
before_install:
  - sudo /usr/bin/Xvfb :99 -ac -screen 0 1024x768x8 & export DISPLAY=":99" 