library(serial)
context("Function failures")
err_msg1 <- paste("[tcl] couldn\'t open ", '"', "/dev/com1", '":', " no such file or directory.\n", sep = "")
err_msg2 <- paste("[tcl] can\'t read ", '"',"sdev com1", '":', " no such variable.", sep = "")
con <- serialConnection()
test_that("all functions are accessible", {
  expect_error(open(con))
  expect_error(read_data(con))
  expect_error(write_data(con, 'test'))
  #expect_error(write_data(con, 3)) # errors *and* warnings
  expect_error(read.serialConnection(con))
  expect_error(write.serialConnection(con, 'test'))
  #expect_error(write.serialConnection(con, 3))
  expect_error(close(con))
})